#!/bin/sh
# Whiff - a better which for when which whiffs
# Copyright (C) 2021 Jon-Erik G. Storm
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
if [ -z "$1" ]
then
   echo "No parameters specified, displaying help."
   echo "Usage: whiff [-asp] \n \
   -a : List all instances of executables found (instead of just the first one of each).\n \
   -s : No output, just return 0 if all of the executables are found, or 1 if some were not found.\n \
   -p : Limit search to \$PATH, just like which." 
fi
files=`echo $@ | sed 's/-a//g' | sed 's/-s//g' | sed 's/-p//g'`
whichflags=`echo $@ | sed 's/-p//g'`
for i in $@
    do
       case $i in
            -p)
                which $whichflags
                break
                ;;
            -a)
                which $whichflags
                for i in $files
                do
                    if	mdfind \(kMDItemDisplayName=="$i"\) \&\& \(kMDItemContentType==public.unix-executable\)
		            then
			            break
		            else
			            find / -perm a=x -perm a=r -iname $i 2>&1 | grep -v -e "Permission denied" -e "Operation not permitted" -e "No such file or directory"
		            fi
                done
                break
                ;;
            *)
                if which $whichflags
                then
                    exit
                fi
                echo "Not found in path, searching filesystem."
                for i in $files
                do
			    if  mdfind kMDItemDisplayName==$i kMDItemContentType==public.unix-executable
                then
                   	break
                else
                    find / -perm a=x -perm a=r -iname $i 2>&1 | grep -v -e "Permission denied" -e "Operation not permitted" -e "No such file or directory"
                fi
                done
                ;;
       esac
    done